config/routes.rb
# config/routes.rb

module Span
  Engine.routes.draw do
    # Added Actions
    def set_member_actions
      member do
        get :seo_settings
        get :seo_settings
        put :update_seo_settings
        patch :update_seo_settings
      end
    end

    def set_collection_actions
      collection do
        get :all
        get :unpublished
        post :sortable
      end
    end

    def set_preview
      member do
        get :preview
      end
    end

    # Static Pages
    root "pages#home"
    resource :pages, path: "/" do
      get :home
    end

    resource :administrator
    resource :session
    resources :reset_passwords
    get "login", to: "sessions#new", as: "login"
    get "logout", to: "sessions#destroy", as: "logout"

    resource :design do
      get :card
      get :list
      get :grid
      get :form
    end

    # Single resources
    resource :settings, only: [:show, :edit, :update, :seo_settings]
    resource :biography, only: [:show, :edit, :update, :seo_settings] do
      set_preview
      set_member_actions
    end

    # Multiple resources
    resources :timelines do
      set_preview
      set_member_actions
      set_collection_actions
    end
    resources :services do
      set_preview
      set_member_actions
      set_collection_actions
    end
    resources :contacts do
      set_member_actions
      set_collection_actions
    end
    resources :billboards do
      set_collection_actions
    end
    resources :networks do
      set_collection_actions
    end

    resource :timeline_settings
    resource :service_settings
    resource :contact_settings

    # CSV Exports
    resources :subscribers
  end
end

app/models/span/administrator.rb
# app/models/span/administrator.rb

module Span
  class Administrator < ActiveRecord::Base
    has_secure_password

    include SetSlug
    include StringGenerator
    include AuthTokenGenerator
    include ResetPasswordTokenGenerator

    before_validation :generate_auth_token, on: :create, uniqueness: true

    # Validations
    validates :name, presence: true
    validates :surname, presence: true
    validates :username, presence: true
    validates :email, presence: true, uniqueness: :true, email: true
    validates :password, length: { in: 8..16 }, allow_nil: true

    def send_reset_password
      generate_reset_password_token(:reset_password_token)
      self.reset_password_sent_at = Time.zone.now
      save!
      # ResetPasswordJob.set(wait: 30.seconds).perform_later(self)
      ResetPasswordMailer.reset_password(self).deliver_later
    end
  end
end

app/models/span/billboard.rb
# apps/models/span/billboard.rb

module Span
  class Billboard < ActiveRecord::Base
    include Lists
    include SetSlug
    include StringGenerator
    include SortablePosition

    # Uploaders
    mount_uploader :imagebox, BillboardUploader
  end
end

app/models/span/biography.rb
# apps/models/span/biography.rb

module Span
  class Biography < ActiveRecord::Base
    include SetSlug
    include StringGenerator
    include DefaultValidations

    # Uploaders
    mount_uploader :imagebox, ImageUploader
  end
end

app/models/span/contact.rb
# apps/models/span/contact.rb

module Span
  class Contact < ActiveRecord::Base
    include Lists
    include SetSlug
    include StringGenerator
    include SortablePosition
    include DefaultValidations

    # Uploaders
    mount_uploader :imagebox, ImageUploader
  end
end

app/models/span/contact_setting.rb
# apps/models/span/contact_setting.rb

module Span
  class ContactSetting < ActiveRecord::Base
    include SetSlug
    include StringGenerator
  end
end

app/models/span/network.rb
# apps/models/span/network.rb

module Span
  class Network < ActiveRecord::Base
    include Lists
    include SetSlug
    include StringGenerator
    include SortablePosition
    include DefaultValidations
  end
end

app/models/span/service.rb
# apps/models/span/service.rb

module Span
  class Service < ActiveRecord::Base
    include Lists
    include SetSlug
    include StringGenerator
    include SortablePosition
    include DefaultValidations

    # Uploaders
    mount_uploader :imagebox, ImageUploader
  end
end

app/models/span/service_setting.rb
# apps/models/span/service_setting.rb

module Span
  class ServiceSetting < ActiveRecord::Base
    include SetSlug
    include StringGenerator
  end
end

app/models/span/setting.rb
# apps/models/span/setting.rb

module Span
  class Setting < ActiveRecord::Base
    include SetSlug
    include StringGenerator

    # Uploaders
    mount_uploader :seo_imagebox, ImageUploader
    mount_uploader :sitemapbox, SitemapUploader
    mount_uploader :documentbox, DocumentUploader

    # Validations
    validates :seo_title, presence: true
    validates :seo_description, presence: true
    validates :seo_tags, presence: true
  end
end

app/models/span/subscriber.rb
# app/models/span/subscriber.rb

module Span
  class Subscriber < ActiveRecord::Base
    include SetSlug
    include StringGenerator

    def self.to_csv
      attributes = %w{email}
      CSV.generate(headers: true) do |csv|
        csv << attributes
        all.each do |subscriber|
          csv << attributes.map{ |attr| subscriber.send(attr) }
        end
      end
    end
  end
end

app/models/span/timeline.rb
# apps/models/span/timeline.rb

module Span
  class Timeline < ActiveRecord::Base
    include Lists
    include SetSlug
    include StringGenerator
    include SortablePosition
    include DefaultValidations

    # Uploaders
    mount_uploader :imagebox, ImageUploader
  end
end

app/controllers/span/administrators_controller.rb
# app/controllers/span/administrators_controller.rb

module Span
  class AdministratorsController < Span::ApplicationController
    before_action :set_administrator, only: [:show, :edit, :update]

    # GET span/administrator/slug
    def show
      redirect_to span.edit_administrator_path
    end

    # GET span/administrator/slug/edit
    def edit
    end

    # PATCH/PUT span/administrator/slug
    def update
      if @administrator.update(administrator_params)
        flash[:success] = "Administrator was successfully updated."
        redirect_to edit_administrator_path
      else
        render :edit
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_administrator
      @administrator = current_administrator
    end

    # Only allow a trusted parameter "white list" through.
    def administrator_params
      params.require(:administrator).permit(
        :name,
        :surname,
        :username,
        :email,
        :password,
        :password_confirmation
      )
    end
  end
end

app/controllers/span/application_controller.rb
# apps/controllers/span/application_controller.rb

module Span
  class ApplicationController < ActionController::Base
    # Specify so all gems that require
    # Span can reach the proper layout.
    layout "span/application"

    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception

    # Lock "adminboard"
    before_action :authorize_administrator

    private

    # Setup the current_administrator method.
    def current_administrator
      @current_administrator ||= Administrator.find_by_authentication_token!(session[:authentication_token]) if session[:authentication_token]
    end

    # Verifies if the Administrator is Logged in or not.
    def authorize_administrator
      redirect_to span.login_path if current_administrator.nil?
    end

    # Creates the current_administrator.
    helper_method :current_administrator
  end
end

app/controllers/span/billboards_controller.rb
# apps/controllers/span/billboards_controller.rb

module Span
  class BillboardsController < Span::ApplicationController
    include Resources

    # GET span/billboards
    def index
      @billboards = BillboardDecorator.decorate_collection Billboard.published_all
    end

    # GET span/billboards/all
    def all
      @billboards = BillboardDecorator.decorate_collection Billboard.list_all
      render :index
    end

    # GET span/billboards/unpublished
    def unpublished
      @billboards = BillboardDecorator.decorate_collection Billboard.unpublished_all
      render :index
    end

    # GET span/billboards/slug
    def show
      redirect_to span.edit_billboard_path(@billboard)
    end

    # GET span/billboards/new
    def new
      @billboard = Billboard.new
    end

    # GET span/billboards/slug/edit
    def edit
    end

    # POST span/billboards
    def create
      @billboard = Billboard.new billboard_params
      @positions = Billboard.pluck(:position).compact
      @positions << 0
      @billboard.position = (@positions.min - 1)
      if @billboard.save
        flash[:success] = "Billboard was successfully created."
        redirect_to span.billboards_path
      else
        render :new
      end
    end

    # PATCH/PUT span/billboards/slug
    def update
      if @billboard.update billboard_params
        flash[:success] = "Billboard was successfully updated."
        redirect_to span.edit_billboard_path(@billboard)
      else
        render :edit
      end
    end

    # DELETE span/billboards/slug
    def destroy
      @billboard.destroy
      flash[:success] = "Billboard was successfully destroyed."
      redirect_to span.billboards_path
    end

    # SORTABLE span/billboards
    def sortable
      Billboard.sort_position params[:billboard]
      render nothing: true
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_resources
      @billboard = Billboard.find_by_slug! params[:id]
    end

    # Only allow a trusted parameter "white list" through.
    def billboard_params
      params.require(:billboard).permit(
        :title,
        :description,
        :path,
        :namepath,
        :imagebox,
        :remove_imagebox,
        :position,
        :published
      )
    end
  end
end

app/controllers/span/biographies_controller.rb
# apps/controllers/span/biographies_controller.rb

module Span
  class BiographiesController < Span::ApplicationController
    include Resource

    # GET span/biography/slug
    def show
      redirect_to span.edit_biography_path
    end

    # GET span/biography/slug/edit
    def preview
    end

    # GET span/biography/slug/edit
    def edit
    end

    # PATCH/PUT span/biography/slug
    def update
      if @biography.update biography_params
        flash[:success] = "Biography was successfully updated."
        redirect_to span.edit_biography_path
      else
        render :edit
      end
    end

    # GET span/biography/slug/edit
    def seo_settings
    end

    # PATCH/PUT span/timelines/slug
    def update_seo_settings
      if @biography.update_attributes biography_params
        flash[:success] = "SEO Settings were successfully updated."
        redirect_to span.seo_settings_biography_path(@biography)
      else
        render :edit
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_resource
      @biography = Biography.first!
    end

    # Only allow a trusted parameter "white list" through.
    def biography_params
      params.require(:biography).permit(
        :title,
        :description,
        :body,
        :imagebox,
        :remove_imagebox,
        :published,

        # SEO Settings
        :seo_title,
        :seo_description,
        :seo_tags,
        :seo_imagebox
      )
    end
  end
end

app/controllers/span/contact_settings_controller.rb
# apps/controllers/span/contact_settings_controller.rb

module Span
  class ContactSettingsController < Span::ApplicationController
    include Resource

    # GET span/contact_settings/slug
    def show
      redirect_to edit_contact_settings_path
    end

    # GET span/contact_settings/slug/edit
    def edit
    end

    # PATCH/PUT span/contact_settings/slug
    def update
      if @contact_settings.update contact_settings_params
        flash[:success] = "Contact Setting was successfully updated."
        redirect_to span.contact_settings_path
      else
        render :edit
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_resource
      @contact_settings = ContactSetting.first!
    end

    # Only allow a trusted parameter "white list" through.
    def contact_settings_params
      params.require(:contact_setting).permit(
        # SEO Settings
        :seo_title,
        :seo_description,
        :seo_tags,
        :seo_imagebox
      )
    end
  end
end

app/controllers/span/contacts_controller.rb
# apps/controllers/span/contacts_controller.rb

module Span
  class ContactsController < Span::ApplicationController
    include Resources

    # GET span/contacts
    def index
      @contacts = ContactDecorator.decorate_collection Contact.published_all
      render :index
    end

    # GET span/contacts/all
    def all
      @contacts = ContactDecorator.decorate_collection Contact.list_all
      render :index
    end

    # GET span/contacts/unpublished
    def unpublished
      @contacts = ContactDecorator.decorate_collection Contact.unpublished_all
      render :index
    end

    # GET span/contacts/new
    def new
      @contact = Contact.new
    end

    # POST span/contacts
    def create
      @contact = Contact.new contact_params
      @positions = Contact.pluck(:position).compact
      @positions << 0
      @contact.position = (@positions.min - 1)
      if @contact.save
        flash[:success] = "Contact was successfully created."
        redirect_to span.contacts_path
      else
        render :new
      end
    end

    # GET span/contacts/slug/edit
    def edit
    end

    # PATCH/PUT span/contacts/slug
    def update
      if @contact.update(contact_params)
        flash[:success] = "Contact was successfully updated."
        redirect_to span.edit_contact_path(@contact)
      else
        render :edit
      end
    end

    # GET span/contacts/slug/seo_settings
    def seo_settings
    end

    # PATCH/PUT span/contacts/slug
    def update_seo_settings
      if @contact.update_attributes contact_params
        flash[:success] = "SEO Settings were successfully updated."
        redirect_to span.seo_settings_contact_path(@contact)
      else
        render :edit
      end
    end

    # DELETE span/contacts/slug
    def destroy
      @contact.destroy
      flash[:success] = "Contact was successfully destroyed."
      redirect_to span.contacts_path
    end

    # SORTABLE span/contacts
    def sortable
      Contact.sort_position params[:contact]
      render nothing: true
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_resources
      @contact = Contact.find_by_slug! params[:id]
    end

    # Only allow a trusted parameter "white list" through.
    def contact_params
      params.require(:contact).permit(
        :title,
        :name,
        :surname,
        :address,
        :country,
        :city,
        :postcode,
        :fax,
        :phone,
        :mobile,
        :email,
        :path,
        :pathname,
        :imagebox,
        :remove_imagebox,
        :position,
        :published,

        # SEO Settings
        :seo_title,
        :seo_description,
        :seo_tags,
        :seo_imagebox
      )
    end
  end
end

app/controllers/span/designs_controller.rb
# apps/controllers/span/designs_controller.rb

module Span
  class DesignsController < Span::ApplicationController
    def card
    end
    def list
    end
    def grid
    end
    def form
    end
  end
end

app/controllers/span/networks_controller.rb
# apps/controllers/span/networks_controller.rb

module Span
  class NetworksController < Span::ApplicationController
    include Resources

    # GET span/networks
    def index
      @networks = NetworkDecorator.decorate_collection Network.published_all
      render :index
    end

    # GET span/networks/all
    def all
      @networks = NetworkDecorator.decorate_collection Network.list_all
      render :index
    end

    # GET span/networks/unpublished
    def unpublished
      @networks = NetworkDecorator.decorate_collection Network.unpublished_all
      render :index
    end

    # GET span/networks/new
    def new
      @network = Network.new
    end

    # GET span/networks/slug/edit
    def edit
    end

    # POST span/networks
    def create
      @network = Network.new network_params
      @positions = Network.pluck(:position).compact
      @positions << 0
      @network.position = (@positions.min - 1)
      if @network.save
        flash[:success] = "Network was successfully destroyed."
        redirect_to span.networks_path
      else
        render :new
      end
    end

    # PATCH/PUT span/networks/slug
    def update
      if @network.update network_params
        flash[:success] = "Network was successfully updated."
        redirect_to span.networks_path
      else
        render :edit
      end
    end

    # DELETE span/networks/slug
    def destroy
      @network.destroy
      flash[:success] = "Network was successfully destroyed."
      redirect_to span.networks_path
    end

    # SORTABLE span/networks
    def sortable
      Network.sort_position params[:network]
      render nothing: true
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_resources
      @network = Network.find_by_slug! params[:id]
    end

    # Only allow a trusted parameter "white list" through.
    def network_params
      params.require(:network).permit(
        :title,
        :path,
        :imagebox,
        :position,
        :published
      )
    end
  end
end

app/views/span/contacts/_actions.html.haml
-# app/views/span/billboards/_actions.html.haml

.actions
  .actionsBox
    - if params[:action] == "index" || params[:action] == "unpublished" || params[:action] == "all"
      .actionsList
        = link_to "New Contact", new_contact_path

app/views/span/contacts/_breadcrumbs.html.haml
-# app/views/span/contacts/_breadcrumbs.html.haml

.breadcrumbs
  .breadcrumbsBox
    .breadcrumbsList
      - if params[:action] == "index" || params[:action] == "unpublished" || params[:action] == "all"
        = link_to "Dashboard", span.root_path
      - elsif params[:action] == "seo_settings" || params[:action] == "update_seo_settings"
        = link_to "Go Back", span.edit_contact_path(@contact)
      - else
        = link_to "Go Back", span.contacts_path

app/views/span/contacts/_cards.html.haml
-# app/views/span/contacts/_cards.html.haml

.card.medium
  %ul#ajaxBox.cardBox.sortable{ "data-update-url" => sortable_contacts_path }
    - if @contacts.blank?
      = render partial: "blocks/span/empty"
    - else
      = render partial: "contact", collection: @contacts, as: :object

app/views/span/contacts/_contact.html.haml
-# app/views/span/contacts/_contact.html.haml

%li.cardList{ id: "contact_#{ object.id }" }
  .top
    %nav.misc
      %ul.miscBox
        = object.get_destroy_btn
        = object.get_handle_btn
        = object.get_edit_btn
  .middle
    = object.get_title
  .bottom
    %nav.misc
      %ul.miscBox
        = object.get_published_status
        = object.get_path

app/views/span/contacts/_form.html.haml
-# app/views/span/contacts/_form.html.haml

= form_for object, html: {multipart: true, autocomplete: :off, class: "form"} do |f|
  %fieldset.formBox
    .formItem.formWrap12
      %legend
        Title
        %i *
      = f.text_field :title

    .formItem.formWrap06
      %legend Name
      = f.text_field :name

    .formItem.formWrap06
      %legend Surname
      = f.text_field :surname

    .formItem.formWrap12
      %legend Address
      = f.text_field :address

    .formItem.formWrap04
      %legend Country
      = f.text_field :country

    .formItem.formWrap04
      %legend City
      = f.text_field :city

    .formItem.formWrap04
      %legend Postcode
      = f.text_field :postcode

    .formItem.formWrap04
      %legend Fax
      = f.text_field :fax

    .formItem.formWrap04
      %legend Phone
      = f.text_field :phone

    .formItem.formWrap04
      %legend Mobile
      = f.text_field :mobile

    .formItem.formWrap06
      %legend Email
      = f.text_field :email

    .formItem.formWrap06
      %legend Path
      = f.text_field :path

    -# Closing Wrap
    .wrap
      .formItem.formWrap02
        = submit_tag "Save"

      .formItem.formWrap02
        %legend Status
        = f.check_box :published
        %p.label Published

      - unless object.imagebox.blank?
        .formItem.formWrap02
          %legend Image
          = link_to "", object.imagebox_url, "data-lightbox" => object.imagebox, class: "filePreview"
          = f.check_box :remove_imagebox
          %p.label
            %small Delete?

      .formItem.formWrap05
        %legend Imagebox
        .fileUpload
          = f.file_field :imagebox, class: "upload"
        %p.fileFormat Formats: jpg, jpeg, png & gif

      .formItem.formWrap12
        %p.note
          %i * Required Fields

app/views/span/contacts/_group.html.haml
-# app/views/span/contacts/_group.html.haml

.group
  .groupBox
    .groupList
      = link_to "Published", contacts_path, remote: true
    .groupList
      = link_to "Unpublished", unpublished_contacts_path, remote: true
    .groupList
      = link_to "All", all_contacts_path, remote: true

app/views/span/contacts/_header.html.haml
-# app/views/span/contacts/_header.html.haml

.wrap.atpD.abpD
  = render partial: "breadcrumbs"
  = render partial: "tabs"
  = render partial: "page_header"
  - if params[:action] == "index" || params[:action] == "unpublished" || params[:action] == "all"
    = render partial: "group"
    = render partial: "actions"

app/views/span/contacts/_page_header.html.haml
-# app/views/span/contacts/_page_header.html.haml

.pageHeader
  .pageHeaderBox
    .pageHeaderItem
      .pageHeaderTitle
        - if params[:action] == "index"
          %h1#ajaxTitle Published Contacts
        - if params[:action] == "unpublished"
          %h1#ajaxTitle Unpublished Contacts
        - if params[:action] == "all"
          %h1#ajaxTitle All Contacts
        - if params[:action] == "new" || params[:action] == "create"
          %h1 Add New Contact
        - if params[:action] == "edit" || params[:action] == "update"
          %h1 Edit Contact
        - if params[:action] == "seo_settings" || params[:action] == "update_seo_settings"
          %h1= "SEO Settings for: " + @contact.title

app/views/span/contacts/_seo_form.html.haml
-# app/views/span/timelines/_form.html.haml

= form_for object, url: update_seo_settings_contact_path(object), html: { multipart: true, autocomplete: :off, class: "form" } do |f|
  %fieldset.formBox
    .formItem.formWrap12
      %legend Title
      = f.text_field :seo_title

    .formItem.formWrap12
      %legend Description
      = f.text_area :seo_description, class: "small"

    .formItem.formWrap12
      %legend Tags
      = f.text_field :seo_tags

    -# Closing Wrap
    .wrap
      .formItem.formWrap02
        = submit_tag "Save"

app/views/span/contacts/_tabs.html.haml
-# app/views/span/contacts/_tabs.html.haml

.tabs
  .tabsBox
    - if params[:action] == "index" || params[:action] == "unpublished" || params[:action] == "all"
      .tabsList
        = link_to "SEO Settings", span.edit_contact_settings_path
    - if params[:action] == "show" || params[:action] == "edit" || params[:action] == "update"
      .tabsList
        = link_to "SEO Settings", span.seo_settings_contact_path
    = render partial: "blocks/span/website_status"

app/views/span/contacts/index.html.haml
-# app/views/span/contacts/index.html.haml

= render partial: "header"
= render partial: "cards"

app/views/span/contacts/index.js.haml
-# app/views/span/contacts/active.js.haml

-# Page Header
- if params[:action] == "index"
  ! $("#ajaxTitle").html("#{"Published Contacts"}");
- if params[:action] == "unpublished"
  ! $("#ajaxTitle").html("#{"Unpublished Contacts"}");
- if params[:action] == "all"
  ! $("#ajaxTitle").html("#{"All Contacts"}");

-# Cards
- if @contacts.blank?
  ! $("#ajaxBox").html("#{j render partial: "blocks/span/empty"}");
- else
  ! $("#ajaxBox").html("#{ j render partial: "contact", collection: @contacts, as: :object }");

app/views/span/contacts/new.html.haml
-# app/views/span/contacts/new.html.haml

= render partial: "header"
= render partial: "blocks/span/errors", locals: { object: @contact }
= render partial: "form", locals: { object: @contact }

app/views/span/contacts/seo_settings.html.haml
-# app/views/span/contacts/edit.html.haml

= render partial: "header"
= render partial: "blocks/span/errors", locals: { object: @contact }
= render partial: "seo_form", locals: { object: @contact }